### PR TITLE
[Work in Progress] add a simple test

### PR DESCRIPTION
**Pull request by sankargorthi**
Adds a test folder with a simple app to test the bundler. Outputs to the `build` folder.

### CODE REVIEW

**Comment by sankargorthi** [comment]
Need to get assets copied over as well.

**Comment by timaschew** [comment]
thanks, I had the same idea some months ago.
But I would prefer to put it into its own repo.
And what you think about to rename the `app` local into `core` or something like that, to clearify that it's a shared module?

**Comment by sankargorthi** [comment]
Sure. I don't mind. This was just an exercise in seeing it work.

**Comment by sankargorthi** [comment]
Ok, I think I have assets working. Do you have a name for the bundler test repo that you prefer? I would just go for "componentjs/bundler-example"

**Comment by timaschew** [comment]
yep, the name is fine: https://github.com/componentjs/bundler-example

**Pull request closed without merging**
